### ISSUE TITLE
Figma

### ISSUE THREAD

**Issue by khanmzeeshan** [khanmzeeshan/307Project#2]
Prototype wireframe

**Comment by khanmzeeshan** [comment]
Design web pages to show app flow. Each page can be determined from the use case diagram.
Features:
1. View Dashboard
2. Create To Do List: add 
3. Import/Sync
4. Notify User
5. Login

**Comment by khanmzeeshan** [comment]
Figma Link: https://www.figma.com/file/ynIlAHGIFXpIE00SUkjtA9/Tasky?node-id=0%3A1

**Comment by kpinnipa** [comment]
UI Kit for Icons, Buttons, etc. : https://www.figma.com/file/52L6hdO5GuD3nng47OnKxO/Ui-Kit-(Community)?node-id=164%3A5031

**Comment by khanmzeeshan** [comment]
Figma Design suggested in new frame addressing the side bar and page navigation options.

**Comment by kpinnipa** [comment]
Time Estimate: 3 hours
Actual: 5 hours
