### ISSUE TITLE
Logo and Name

### ISSUE THREAD

**Issue by kpinnipa** [khanmzeeshan/307Project#3]
Brainstorm name and logo for our web application.

**Comment by kpinnipa** [comment]
Finalize the App Name: 
- Tasky?
- MyDay?
- Caldr etc

**Comment by asmitasharmaa** [comment]
App Name: CalPal
Logo: Updated on Figma

**Comment by asmitasharmaa** [comment]
The logo and design are almost finalized. We have a good starting point, we can update this later if we end up modifying the design.
