### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by kpinnipa** [khanmzeeshan/307Project#9]
Figure out what to use for profile creation as well as login/security.

**Comment by khanmzeeshan** [comment]
Decisions:
1. Calendar sign on linked through API
2. Application Sign on: user specific login for app content

**Comment by asmitasharmaa** [comment]
Google Auth: [(https://medium.com/@maartendebaecke2/mern-stack-implementing-sign-in-with-google-made-easy-9bfdfe00d21c)]

**Comment by ashingtondc** [comment]
Time Estimate: 2 hours
Time taken: 4 hours
